name: CI

on:
  push:
    branches: [main]
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

jobs:
  format:
    uses: pxlrbt/laravel-standards/.github/workflows/format.yml@v1
    permissions:
      contents: write
    secrets:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

  analyse:
    needs: format
    uses: pxlrbt/laravel-standards/.github/workflows/analyse.yml@v1
    permissions:
      contents: read
    secrets:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

  tests:
    needs: format
    uses: pxlrbt/laravel-standards/.github/workflows/tests.yml@v1
    permissions:
      contents: read
    secrets:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
    with:
      shards: '[1]'

  mutation:
    needs: format
    uses: pxlrbt/laravel-standards/.github/workflows/mutation.yml@v1
    permissions:
      contents: read
    secrets:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

  coverage:
    needs: format
    uses: pxlrbt/laravel-standards/.github/workflows/coverage.yml@v1
    permissions:
      contents: read
    secrets:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
